# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

target 'Messenger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end


